import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Orbitron, Nunito } from "next/font/google";
import "./globals.css";

import ReduxProvider from "@/component/provider/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});
const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${orbitron.variable} ${nunito.variable} antialiased bg-linear-to-bl from-[#519ff1]/70 via-[#f7f7f7] to-[#dcdbdb]`}
      >
        <ReduxProvider> {children}</ReduxProvider>
      </body>
    </html>
  );
}
